services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - /containers/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
